### ISSUE TITLE
SD Manual: Bad link Joining the Opencpn Organization

### ISSUE THREAD

**Issue by rgleason** [Rasbats/managed_plugins#16]
Joining the OpenCPN Organization

Has a bad link that fails. See

I think it is

After you login you will automatically find the invite within the organization invites section of your user settings: https://cloudsmith.io/user/settings/orgs/invites/

If you are not logged in!

**Comment by leamas** [comment]
A lot o things missing here, like "See" and "I think it is".  

Where is this bad link? exactly?

**Comment by rgleason** [comment]
Well yes. You must be logged in. So it is ok
