### ISSUE TITLE
Use "Copy using git" in examples.

### ISSUE THREAD

**Issue by leamas** [Rasbats/managed_plugins#2]
The current examples uses a loose "copy" to copy files from shipdriver (sort of master) to new plugins. There are two problems here:

  - Users need to checkout a private copy of the shipdriver repo. While simple, it is not natural
    and also creates a real problem to keep it updated.
  - On WIndows, the permissions are not retained leading to complicated explanations, log file excerpts 
    and what not 

I suggest that we describe the process to  copy files from the shipdriver master (sort of) like this. 

  - First create a new shipdriver remote  (if not already in place)  and update it to current status:
        
           $ git remote add shipdriver https://github.com/Rasbats/shipdriver_pi.git
           $ git remote update shipdriver

  - For example: update the cmake directory:
  
           $ git rm -rf cmake
           $ git checkout shipdriver/master cmake
           $ git commit

These are simple commands to copy, and users should soon understand how to expand the usage pattern. Here are no problems with permissions in windows, so the complicated explanations how to fix these can be dropped.

Just my 5 öre

**Comment by leamas** [comment]
Expanding on above: Here are the commands to import all directories from shipdriver in a  new plugin:

    $ git remote add shipdriver https://github.com/Rasbats/shipdriver_pi.git
    $ git remote update shipdriver
    $ git rm -rf  .circleci build-deps ci flatpak libs mingw
    $ git checkout shipdriver/master  .circleci build-deps ci flatpak libs mingw
    $ git mv flatpak/org.opencpn.opencpn.plugin.ShipDriver.yaml \
           flatpak/org.opencpn.opencpn.plugin.TideFinder.yaml
    $ git commit 

These commands are easy to just copy-paste without much thought, and also works on all platforms. It should be compared to the somewhat lengthy description in https://github.com/Rasbats/managed_plugins/wiki/Plugin-Adaptation#replaceadd-files-to-enable-ci-continuous-integration, which still doesn't cover how to create a clone of shipdriver and to update it before use.  And immediately runs into the permissions problem on windows (still more explanations...)

Thoughts?

**Comment by Rasbats** [comment]
Still thinking... Liking this, but where is the 'cmake' directory?

**Comment by leamas** [comment]
Well, here are certainly rough corners, the missing cmake directory being one of them (and all plain files, also missing). But the important thing is if you like the overall idea. If so, I can try to document more thoroughly in the wiki, at first as an alternative but in the end aimed to replace some parts.  

So, if you like this, should I try to put some flesh on the bones in the wiki?

**Comment by Rasbats** [comment]
Please go ahead with the wiki... could you move the parts being replaced to another page(s), so the user can see what the alternative is to using git? 
And the justification for git can be included... keeping in sync with ShipDriver developments. 
And the permissions benefits for using git.

**Comment by leamas** [comment]
ok. I will not remove anything until we talk about, though.

**Comment by leamas** [comment]
Done. Take a look, let's see how we proceed from here.

**Comment by Rasbats** [comment]
Looks good. My GUI tastes are catered for :)

**Comment by leamas** [comment]
Yes, leave this closed. But in the back of my head the obvious solution is mulling: make a script which handles the update. It will probably never be fire and forget, but should be able to do the heavy lifting.
