### ISSUE TITLE
Plugin Adaptation: outdated

### ISSUE THREAD

**Issue by leamas** [Rasbats/managed_plugins#21]
The Plugin Adaptation page list the directories and files to copy when adapting a plugin to the Shipdriver templates. This is now severely outdated and needs to be fixed.

However, to have detailed lists of files like this is hard to maintain as things evolves. The alternative to the detailed, manual description is perhaps to point to the new updates-templates script which basically does the job described here. And, by definition, is updated.

**Comment by leamas** [comment]
@rasbats: thoughts?

**Comment by Rasbats** [comment]
Had a Testplugin based plugin to move to the ShipDriver template. _update-templates_ did not help too much and I did manual copying. After a draft layout I was able to run _update-templates_. 

There are a lot of variables. Is it a legacy package plugin? Does it use another template? Is it a new plugin based on, say DR_pi?

Another factor is the ability of the developer to run scripts.

>The Plugin Adaptation page list the directories and files to copy when adapting a plugin to the Shipdriver templates. This is now severely outdated and needs to be fixed.

Absolutely. Time is scarce atm as I try and get more plugins into Android and update for MacOS.

**Comment by leamas** [comment]
>  After a draft layout I was able to run update-templates

Is that to say that update_templates does not create the directories needed if they do not exist?

**Comment by Rasbats** [comment]
>Is that to say that update_templates does not create the directories needed if they do not exist?

Not sure. I would need play with one of Rick's.

**Comment by leamas** [comment]
I have made a note to test on  a testplugin-based plugin. This is not a use-case I have anticipated, so that it fails is not unexpected. I can take this ball.

**Comment by leamas** [comment]
Let's focus on getting update-templates in a usable shape also for new installs in next release, presumably 3.0.1. 

After this is released, we change the description here to run the script instead, easier for both users and maintainers.

For now, probably just add a prominent note saying that the description is outdated.

**Comment by Rasbats** [comment]
Still unclear how a particular version of ShipDriver is used. We have master and sd3.0.0
update-templates uses master. Why have sd3.0.0?

**Comment by leamas** [comment]
update-templates uses master by default.  However `update-templates shipdriver/v3.0` does the right thing.

sd3.0.0 is just to define the actual release. Without a tag we are basically lost. I have been considering adding the ability to use also a tag as an argument to update-templates. Not there yet, though.

**Comment by leamas** [comment]
I have made a new page on Code adaptation in the developer manual: https://opencpn-manuals.github.io/main/ocpn-dev-manual/5.3.1/Plugin-Pi-Adaptation.html.

It is basically a copy from Plugin-Adaptation.adoc, just added a section and fixed a link or two. Good enough to replace the stuff currently in Plugin-Adaptation.adoc?

You have all commit rights... :)

**Comment by leamas** [comment]
> I have been considering adding the ability to use also a tag as an argument to update-templates. Not there yet, though.

Wrong again. Actually, we are there besides some docs. There  are three ways to run update-templates
  - Just `update-templates` gets last state in master.
  - `update-templates shipdriver/v3.0` gets last commit in the v3.0  branch
  - `update-templates sd3.0.0` gets data as of the tag sd3.0.0 

Yes, I was surprised as well :)

**Comment by Rasbats** [comment]
Tomorrow :}

**Comment by Rasbats** [comment]
>I have made a new page on Code adaptation in the developer manual:

Latest build of the manual has not picked up the changes to the ShipDriver template (managed_plugins) I made.
Could you take a look?

**Comment by Rasbats** [comment]
[commit 6f224b3eaa5d3a8aafe64243f979009343742a54](https://github.com/opencpn-manuals/development/commit/6f224b3eaa5d3a8aafe64243f979009343742a54)

**Comment by leamas** [comment]
IT's probably about branches,  main still uses asciidoc. Have you merged all in master?

**Comment by leamas** [comment]
hm... I should  have checked. From what I see:

  - main is at 9aab6e1, yesterday  12:39:45
  - asciidoc is at 098afab,  Dec 10 17:15:24
 
None of these are 6f224b3eaa5d  , a commit which gihub doesn't seem to be able to resolve.

"Mystified"

Thoughts?

**Comment by Rasbats** [comment]
The problem is that site.yml in development is pointing at the asciidoc branch of managed_plugins. I thought I had changed that but ... I will change it to branch main and build again.

**Comment by leamas** [comment]
OK, I will do the same update in main.

**Comment by leamas** [comment]
main building, development at 6f224b3eaa5, using managed_plugins main branch

**Comment by Rasbats** [comment]
Ok ... things look good.

**Comment by leamas** [comment]
I think we have solved this, for the monet at least. Closing
