### ISSUE TITLE
Re-organize the manual

### ISSUE THREAD

**Issue by leamas** [Rasbats/managed_plugins#22]
Originally this was written as a guide how to port/implement/use the shipdriver templates for a "new" plugin without CI support (or using other templates). So far, so good.

However, I get the feeling the this not only about configuring, here is also some other docs which don't have a natural place in the current structure. What if we did something like this instead:

```
Overview
Installation & configuration
        The shipdriver workflow
        Cloud service changes
        Builders  
            Appveyor
            CircleCI
            Github Actions
            drone.io
            Travis
        Cloud service changes
        Cloudsmith
        Custom Cloudsmith repositories
        Travis
        Github
Metadata flow  
End user usage
Local builds
``` 
Perhaps we should find a new place for the "Code changes" page. This is actually not related to the shipdriver templates, it's is generic information which is the same for shipdriver, testplugin or something else.

**Comment by leamas** [comment]
@Rasbats : thoughts?

**Comment by Rasbats** [comment]
Where does adapting a legacy plugin fit in? Ok ... there are not supposed to be any.

**Comment by leamas** [comment]
The changes needed definitely needs to be documented.  Perhaps we could place it directly in the Plugin development manual, besides  testplugin and shipdriver. Or?

**Comment by Rasbats** [comment]
This page needs moving:
[https://opencpn-manuals.github.io/main/ocpn-dev-manual/5.3.1/pm-tp-adapt-plugin.html](https://opencpn-manuals.github.io/main/ocpn-dev-manual/5.3.1/pm-tp-adapt-plugin.html)
This could be merged with this from:
[https://opencpn-manuals.github.io/main/AlternativeWorkflow/CodeChange.html](https://opencpn-manuals.github.io/main/AlternativeWorkflow/CodeChange.html)
And the result moved outside the two templates.

**Comment by leamas** [comment]
Right. Lot's of work ahead.  But we seem to agree, question is just when there is time for someone to fix it. Me? Not now. 

If I start working on it, I'll assign it to myself. If you do, please do the same.

**Comment by leamas** [comment]
BTW: He who is silent agrees... (is there even such an English saying?)

Since you don't mention the overall re-organization I assume that you agree on it. Else, this is the time to talk about it.

**Comment by Rasbats** [comment]
"Tacit agreement". 

> I assume that you agree on it

Agree that work is needed.

**Comment by Rasbats** [comment]
@leamas : I can give this some time. Bit confused about which branch of this repo to use. Some recent changes to asciidoc but the manual draws on main. Do we need to merge asciidoc into main before I start?

**Comment by Rasbats** [comment]
The edit url is for asciidoc but I see main in _site.yml_.

**Comment by leamas** [comment]
main currently draws from asciidoc. I actually think this asciidoc  branch is a legacy we preferably should get rid off by merging it into master or main (whatever used) and update the references in main/site.yml and plugins/site.yml

**Comment by Rasbats** [comment]
> update the references in main/site.yml and plugins/site.yml

Done. 

First cut of the new layout for the ShipDriver template in the development manual has been made. Needs another pair of eyes.
@leamas :Need some ideas in the local builds area.

**Comment by Rasbats** [comment]
Some pages showing as 'untitled'. == to change to =.

**Comment by Rasbats** [comment]
I have made a TODO list as an issue. Feel free!

**Comment by leamas** [comment]
Right, I made some notes in there. Let's continue using that list, closing this issue.
