### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/managed_plugins#24]
Summary of edits needed to polish up the ShipDriver Template stuff:

  - ~~Fix untitled pages (= iso ==)~~
  - Custom-cloudsmith-repositories.adoc - reference for Cloud service changes.
  - ~~Update nav.adoc to reflect the overall structure laid out in index.adoc~~
  - ~~Perhaps: Add  reference page describing the builder environment variables, when they are needed, how to find the value but not how to set it . That is, the parts which does not depend on the actual builder.~~
  - ~The info under Github Preparations are partly a duplicate of Automatic Git Push of Metadata, should be linked one way or another instead.~
  - ~~The page on how to install the templates is outdated, has the wrong set of directories and files, does not mention update_templates. Needs to get fixed once most of the update_templates bugs are ironed out.~~

**Comment by leamas** [comment]
@rasbats: time to close?
