### ISSUE TITLE
new-credentials - keys could end up in the wrong directory.

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/managed_plugins#38]
Instructions leave the keys in the _ci_ directory.

```
New ssh key created and encrypted.Todo:

  - Commit the new ssh keys ci/Rasbats.pub and ci/Rasbats.enc.
  - Add the ssh url as GIT_REPO environment variable in builder.
  - Add password as GIT_KEY_PASSWORD environment variable in builder.
  - Add the public key ci/Rasbats.pub below to the github account:
```
Suggest:

```
New ssh key created and encrypted.Todo:
  - Move the ssh keys ci/Rasbats.pub and ci/Rasbats.enc to the build-deps directory.
  - Commit the keys Rasbats.pub and Rasbats.enc.
  - Add the ssh url as GIT_REPO environment variable in builder.
  - Add password as GIT_KEY_PASSWORD environment variable in builder.
  - Add the public key ci/Rasbats.pub below to the github account:

```

**Comment by leamas** [comment]
Isn't this two questions?
- Does new-credentials actually create the keys in ci/ instead of build-deps/? If so, this is a bug which should be fixed.
- After fixing that possible bug, we should update the documentation to use build-desp instead of ci.

**Comment by leamas** [comment]
When I make a try, new-credentials actually stores the key in build-deps in both master and v3.0 branch. Have you any other experiences?

If so, this is just a simple documentation fix: replace _ci_ with _build-deps-, I guess. Or?

**Comment by Rasbats** [comment]
My mistake - TideFinder_pi has not been updated.
