### ISSUE TITLE
Please add a tag.

### ISSUE THREAD

**Issue by leamas** [Rasbats/managed_plugins#8]
Experimenting in the development repo to avoid the need of source-state.sh and friends. 

The development repo import only this one  and the installer docs. One way to keep things stable is to use a git tag instead of a branch. To that end, could you please just tag current  sources, say to v.0.1 and push the tag?

**Comment by Rasbats** [comment]
Done.

**Comment by leamas** [comment]
Thanks. Doesn't matter for now, but next time we tag we should probably update antora.yml's version to match the tag.
