### ISSUE TITLE
Broken links.

### ISSUE THREAD

**Issue by leamas** [Rasbats/managed_plugins#9]
Running checklink on current asciidoc branch  at d195a982  reveals multiple errors. Unfortunately, they of course also pop up when checking the development manual, so any help the get this fixed would be great.

Attaching the log, which also has the command at top. Otherwise, the errors are also visible in the development [full linkcheck] log.
[checklink.log.gz](https://github.com/Rasbats/managed_plugins/files/6988751/checklink.log.gz)

**Comment by Rasbats** [comment]
Ok. Checks with your grep method. Thanks. Update pushed to asciidoc branch.
(asciidoc branch does not follow the contents of the wiki - some other changes need adding to asciidoc idc)

**Comment by leamas** [comment]
Looks much better. Attaching checklink results.
[checklink.log.gz](https://github.com/Rasbats/managed_plugins/files/6991342/checklink.log.gz)

**Comment by leamas** [comment]
Oops... I don't think that was the right log. New attempt here:  [checklink.log.gz](https://github.com/Rasbats/managed_plugins/files/6991582/checklink.log.gz)

**Comment by leamas** [comment]
This is too old data to be meaningful. The links checks are in place providing actual input any time. Closing
